version: '3.9'

services:
  app:
    container_name: app_container
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./db:/app/db
      - ./node_modules:/app/node_modules
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: db_container
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
