version: '3.9'

services:
  app:
    container_name: auth_app
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./db:/app/db
      - ./src:/app/src
    depends_on:
      - migrations

  migrations:
    container_name: auth_migrations
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    depends_on:
      - db

  db:
    container_name: auth_db
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
